### ISSUE TITLE
발사기를 통한 뼛가루 사용

### ISSUE THREAD

**Issue by blue1222** [noonmaru/farm#1]
발사기에 뼛가루를 넣고 작물에 발사하면 뼛가루가 사용되며 작물이 자라는데, 이것을 이용해 타이머를 무시하고 작물이 자라게 할 수 있습니다. 테스트 결과 수박과 호박은 줄기만 자라고 열매가 맺히진 않지만 다른 작물은 거의 다 가능한 것으로 보입니다.

**Comment by noonmaru** [comment]
수정했습니다.

감사합니다~
