### ISSUE TITLE
명령어 질문

### ISSUE THREAD

**Issue by eric236** [noonmaru/farm#6]
대지돈 플러그인 명령어를 모르겠는데 써주실수있나요

**Comment by eric236** [comment]
tap은 3.2.1 kotlin은 1.4.10 protocolLib은 4.5.1 사용중입니다

**Comment by eric236** [comment]
area명령어가 안 먹힙니다

**Comment by realteusu** [comment]
`/area` 명령어는 다른 플러그인입니다. [regions](https://github.com/noonmaru/regions)를 참고해주세요.
